# Generated by Django 4.2.4 on 2023-08-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tag_todo_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
